### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by qihang9903** [bdi-lab/InGram#2]
Hello, may I ask if the msg.txt file in the dataset represents a dynamically segmented training set? How was it generated?

**Comment by jaejunlee714** [comment]
Hello,

Thanks for your interest in our work.
msg.txt file corresponds to F_inf in our paper.
Since dynamic split strategy is "dynamic", we do not have split file.
In our code, we "dynamically" split the train.txt.
Thank you.

Best,
Jaejun Lee

**Comment by qihang9903** [comment]
Hello, thank you very much for your reply! 
Can I understand it this way: 
train.txt=F_tr+T_ tr, 
test.txt=T_test,
val.txt=T_val and msg.txt=F_inf.
Looking forward to your reply!

**Comment by jaejunlee714** [comment]
Yes, you're correct.
Note that train.txt = F_tr+T_tr = E_tr.
Thank you.

Best,
Jaejun Lee

**Comment by qihang9903** [comment]
Thank you!
