### ISSUE TITLE
Academic request

### ISSUE THREAD

**Issue by liangxinyu0514** [bdi-lab/InGram#3]
Hello, I'd like to inquire about how to handle the data files msg.txt, train.txt, valid.txt, and test.txt for this article's dataset when using them with Grail's model.

**Comment by ChanyoungChung** [comment]
Each dataset used in GraIL is provided with two folders: `DATA` and `DATA_ind`.

Our data files correspond to GraIL's data files with the following mapping:

`train.txt` → `DATA/train.txt`
`msg.txt` → `DATA_ind/train.txt`
`valid.txt` → `DATA_ind/valid.txt`
`test.txt` → `DATA_ind/test.txt`

During training, we perform validation on the inference graph. Therefore, we modified `train.py` to perform validation on the inference graph, not on the training graph.

Thanks,
Chanyoung Chung
