### ISSUE TITLE
calculating affinity scores

### ISSUE THREAD

**Issue by ceteri** [bdi-lab/InGram#4]
Thank you, this work is super interesting.

In the paper, _affinity_ scores are described as:
> Briefly speaking, we measure the affinity between two relations by considering how many entities are shared between them and how frequently they share the same entity.

For those of use who are studying this approach, could you please define the scores' calculations in greater detail?

Based on the definition of a _graph of relations_ in the paper, the values for "how many entities are shared between them" and "how frequently they share the same entity" would appear to be the same count every time.

**Comment by jaejunlee714** [comment]
Hello, 

Thanks for your interest in our work!
"How many entities are shared between them" means the "number" of different entities, and "how frequently they share the same entity" means the frequency of each entity. When two relations share the same entity $n$ times, then the former only counts it as 1, while the latter counts it as $n$.
Thank you.

Best,
Jaejun Lee
