### ISSUE TITLE
Dataset Generation

### ISSUE THREAD

**Issue by HarryShomer** [bdi-lab/InGram#7]
Hi,

I really enjoyed your work.

Would you be able to share the code for generating the specific datasets used in your experiments. Basically algorithm 2 in your paper.

Thanks,
Harry

**Comment by jaejunlee714** [comment]
HI, thanks for your interest in our work!
We've uploaded the codes we've used for generating our datasets. the generate_data.py corresponds to the algorithm 2 in our paper.

Best,
Jaejun Lee

**Comment by HarryShomer** [comment]
Thanks for the quick response!
