### ISSUE TITLE
How was NBFNet Trained?

### ISSUE THREAD

**Issue by HarryShomer** [bdi-lab/InGram#9]
Hi,

I have a quick question regarding some experiments in the paper.

You mentioned in Appendix B that for NBFNet and RED-GNN you:
```
"modified all the baseline models except RAILD and RMPI so that the models accept new relations 
since they do not consider new relations at inference time"
```
I was hoping you could give more details as to how this was done.

From my understanding, NBFNet and RED-GNN learn embeddings for all relations during training. This means they won't have those embeddings for the new relations during inference.

In that case, what did you use for the new relations during inference? Was it random embeddings?

Thanks,
Harry

**Comment by jaejunlee714** [comment]
Yes. For the methods that learn relation embeddings, we used random embeddings for the new relations.

**Comment by HarryShomer** [comment]
Thanks!
